### ISSUE TITLE
can't build it...

### ISSUE THREAD

**Issue by fstltna** [shellinabox/shellinabox#533]
I get the following errors:
/home/empireplayer/shellinabox/libhttp/ssl.c:642:(.text+0xa9): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: /home/empireplayer/shellinabox/libhttp/ssl.c:647:(.text+0xc2): undefined reference to `OPENSSL_sk_zero'
/usr/bin/ld: /home/empireplayer/shellinabox/libhttp/ssl.c:657:(.text+0xcc): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: /home/empireplayer/shellinabox/libhttp/ssl.c:658:(.text+0xd9): undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:711: shellinaboxd] Error 1
make[1]: Leaving directory '/home/empireplayer/shellinabox'
make: *** [Makefile:544: all] Error 2

Any ideas? Trying to build on Ubuntu 24.04...

**Comment by coofercat** [comment]
I strongly recommend you format your post properly - it's pretty much impossible to read as it is. If I hadn't got the exact same, I'd have just scrolled right on by.

It also appears you didn't look very hard for solutions. The solution is right here: https://github.com/shellinabox/shellinabox/issues/513

**Comment by EziosWJ** [comment]
i try this code successful #441 

download this code by zip and build it : https://github.com/shellinabox/shellinabox/tree/c32f3d365a0848eb6b3350ec521fcd4d1d098295
