### ISSUE TITLE
cross compile error

### ISSUE THREAD

**Issue by qq57240** [shellinabox/shellinabox#399]
libhttp/ssl.c: In function ‘sslGetNextBIO’:
libhttp/ssl.c:1020:11: error: dereferencing pointer to incomplete type
   return b->next_bio;
           ^
libhttp/ssl.c:1024:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:741: recipe for target 'libhttp/ssl.lo' failed
make[1]: *** [libhttp/ssl.lo] Error 1
make[1]: Leaving directory '/home/jiajia/miwifi/shellinabox-2.20'
Makefile:529: recipe for target 'all' failed
make: *** [all] Error 2

cross compile on ubuntu 16.04 with arm-linux-uclib

**Comment by qq57240** [comment]
it looks like next_bio was not complete defined
i moved lines "return b->next_bio;#else" then it compiled successful.

**Comment by tomtor** [comment]
I noticed the same error with ubuntu 16.04 native compile on an ARM Odroid
C2

Op zo 20 nov. 2016 19:01 schreef qq57240 <notifications@github.com>:

**Comment by KLuka** [comment]
Hi, guys... I think the problem is related to openssl 1.1.0. Can you confirm that?

Possible workaround would be to compile shellinabox with `--disable-runtime-loading` like we are doing it for debian package. But I am not sure...

**Comment by qq57240** [comment]
Hi,Kula
I tried openssl 1.0.1 and 1.1.0, both occured this error.
I noticed the issus #384 early. 
The error occured again after I added the command line "--disable-runtime-loading".

**Comment by KLuka** [comment]
Hm... It is strange that `#if OPENSSL_VERSION_NUMBER <= 0x10100000L` doesn't kick in... Can you check what is happening here?

**Comment by qq57240** [comment]
libtool: compile:  arm-xiaomi-linux-uclibcgnueabi-gcc -DHAVE_CONFIG_H -I. -g -std=gnu99 -Wall -Os -MT libhttp/ssl.lo -MD -MP -MF libhttp/.deps/ssl.Tpo -c libhttp/ssl.c  -fPIC -DPIC -o libhttp/.libs/ssl.o
libhttp/ssl.c: In function ‘sslGetNextBIO’:
libhttp/ssl.c:1020:11: error: dereferencing pointer to incomplete type
   return b->next_bio;
           ^
libhttp/ssl.c:1024:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:741: recipe for target 'libhttp/ssl.lo' failed
make[1]: *** [libhttp/ssl.lo] Error 1
make[1]: Leaving directory '/home/jiajia/miwifi/shellinabox'
Makefile:529: recipe for target 'all' failed
make: *** [all] Error 2

./configure -prefix /home/jiajia/miwifi/sshbox --host=arm-xiaomi-linux-uclibcgn OPENSSL_CFLAGS="-I/home/jiajia/miwifi/openssl101/include" OPENSSL_LIBS="-L/home/jiajia/miwifi/openssl101/lib -lssl -lcrypto" --disable-runtime-loading

cross compile with openssl 1.0.1, got that error again...

**Comment by qq57240** [comment]
@KLuka 
The operator "=" was removed and this erro occured still.
is my command wrong?

**Comment by qq57240** [comment]
please close this issue.
It occurs by my mistake.
OPENSSL_CFLAGS and OPENSSL_LIBS param are not be supported.
CFLAGS and LDFLAGS are correct. Compiled successful with the correct params.

**Comment by tomtor** [comment]
I had the error probably due to an old .configure.

A clean clone and autoreconf -i && .configure && make

compiled fine now on my Ubuntu 16.04 arm system.

Op 12:32 MA 21 Nov 2016 schreef qq57240 <notifications@github.com>:

please close this issue.
It occurs by my mistake.
OPENSSL_CFLAGS and OPENSSL_LIBS param are not be supported.
CFLAGS and LDFLAGS are correct. Compiled successful with the correct params.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/shellinabox/shellinabox/issues/399#issuecomment-261913436>,
or mute the thread

**Comment by KLuka** [comment]
Ok, guys. Thanks for figuring it out ;)
